### ISSUE TITLE
touchpad gestures don't work

### ISSUE THREAD

**Issue by janxkoci** [elementary/browser#107]
### What Happened?

I just did a fresh install of OS 7 and one of the issues I noticed is that Webkit gestures (two-finger swipes) don't work for navigation anymore. This was working fine on OS 6.1.

### Steps to Reproduce

1. Open browser and navigate some websites (e.g. wikipedia).
2. Try two-finger horizontal swipe gestures on multitouch touchpad.
3. Nothing happens.

### Expected Behavior

Gestures shoud work in the browser. The gestures do work elsewhere (e.g. AppCenter or Multitasking view).

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Slimbook Essential 14 (bought in 2020 with elementary OS preinstalled).

**Comment by fayjie92** [comment]
Same issue here.

**Comment by danirabbit** [comment]
Please report this issue upstream, we don't carry any downstream patches related to gestures support https://gitlab.gnome.org/GNOME/epiphany/-/issues
