### ISSUE TITLE
Epiphany does not use dark style (Whether set globally or in the settings itself)

### ISSUE THREAD

**Issue by selwynorren** [elementary/browser#11]
## What Happened
Latest daily build of eOS 6 I set the global theme to dark and it looks amazing (By teh way) I launch Epiphany and the header bars, etc are all still light themed. I entered the settings and noticed under appearance it was set to the light theme. I changed that there as well and yet it all still remains light

## Expected Behavior
For header bars to honour tey global appearance limits, or at minimum for the headers to go dark when seledcted

## Steps to Reproduce
Launch Epiphany - lol

### Logs
Nothing that I can think of, however will gladly supply logs if you can let me know how to run it for that.

## Platform Information
elementaryos-6.0-daily.20210422

**Comment by Exalm** [comment]
It's running in Flatpak, which doesn't have access to the dark preference setting atm. The `org.freedesktop` schema needs to be listed here: https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/settings.c#L234-L243

**Comment by selwynorren** [comment]
I had a thought it may be something like that. So something else I had noticed with flatpack app is they did not have access to anything else ion the system either. Example (In eOS 5.1.7) I have kdenlive installed, when I try and load the system system that set the audio editor and image editor (Audacity and Gimp), both which are flatpacks, kdenlive does not see them at all.

Is this the same sort of issue?

**Comment by Exalm** [comment]
WDYM by see? I don't use kdenlive. That said, it's unrelated to the issue.

**Comment by selwynorren** [comment]
> WDYM by see? I don't use kdenlive. That said, it's unrelated to the issue.

No stress I was just curious, but as you mentioned it unrelated.

**Comment by Exalm** [comment]
No need to cloes it, it's a valid issue.

**Comment by selwynorren** [comment]
> No need to cloes it, it's a valid issue.

Oh okay thanks.

**Comment by danrabbit** [comment]
In the meantime we can probably patch this in our Flatpak until we can get it fixed properly upstream

**Comment by selwynorren** [comment]
Just one additional comment , is gnome web looks very much like the default gnome look of the header bars. It does not look like epiphany at all. Also the Firefox sync tabs is completely blank
