### ISSUE TITLE
bookmark popover is too small

### ISSUE THREAD

**Issue by janxkoci** [elementary/browser#111]
### What Happened?

The current bookmark popover is ridiculously small:

![Snímek z 2023-06-01 15 49 18](https://github.com/elementary/browser/assets/19331850/00954f52-9153-425b-ab21-479da24d6b4b)

I think it used to be bigger just before the GTK4 port arrived. I also downloaded Epiphany Tech Preview where this popover was normal-sized, but after a while (a reboot maybe) the theme of Tech Preview got changed to elementary theme and now the popover is also tiny there.

### Steps to Reproduce

1. Save some bookmark
2. open bookmark popover
3. see for yourself

### Expected Behavior

The popover should have a reasonable size, definitely larger than the current one. I tried to set Ephy Tech Preview theme to Adwaita - it looks _very_ different than when I first downloaded it, but the popover got bigger:

![Snímek z 2023-06-01 15 53 58](https://github.com/elementary/browser/assets/19331850/d0bcd82d-e3b0-40d5-ba75-dbe820e7efad)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by decembre-dhiver** [comment]
Have the same thing
