### ISSUE TITLE
Epiphany has tofus (missing characters) in ja_JP language

### ISSUE THREAD

**Issue by dominichayesferen** [elementary/browser#14]
## What Happened
Upon checking the live session with the locale changed to ja_JP (Japanese), I opened Epiphany to find its font is just tofus.

## Expected Behavior
Japanese characters will be present in Epiphany

## Steps to Reproduce

1. Change the language to Japanese
2. Log out and back in
3. Open Epiphany

![japanese tofus](https://user-images.githubusercontent.com/11057934/116788176-1fcdc380-aaa0-11eb-8e3a-71b55b0d394a.png)

## Platform Information

elementary OS 6 Public Beta (in the Live Session)

**Comment by dominichayesferen** [comment]
Additional information: I don't know if it's because Web lacks a Japanese name in its .desktop file or not, but 'Web' remains 'Web' in the Applications Menu when in Japanese locale.

**Comment by ryonakano** [comment]
I'm not sure why you didn't choose Japanese in the welcome screen shown before you choose to go to the Demo Mode and choose English there and switch to Japanese in System Settings, but FYI choosing Japanese first shows Japanese characters correctly in GNOME Web:

![Screenshot from 2021-05-02 08-18-03](https://user-images.githubusercontent.com/26003928/116834463-363b6280-abf9-11eb-9a76-ece45ec45e8e.png)

This is also true if you installed elementary OS into the device.

**Comment by dominichayesferen** [comment]
After updating, it seems like I can't reproduce this now either. Gonna close it now.
