### ISSUE TITLE
Error during the display of the page

### ISSUE THREAD

**Issue by Angedestenebres** [elementary/browser#15]
Hey :cat: 

When I try to go on a website or even on DuckDuckGo or Google search engines I got this error :

![Capture d’écran_2021-05-01_22-32-47](https://user-images.githubusercontent.com/21110485/116794538-eca22900-aacd-11eb-9a79-cba5e91a5825.png)

However, as you can see my internet connection works and I can apply updates or navigate with Firefox.

OS : elementary 6 build 2021-04-30
VM on VirtualBox version 6.1.16 (from Ubuntu repository)
Tried with liveUSB and after an installation with all updates applied and same issue.
ISO has been checked with sha256sum.

Let me know if you need more information.

**Comment by cassidyjames** [comment]
This is the very first regerssion card on the Odin project board, which we link to from the beta download website and announcement blog post. Please review that project board before filing issues.

https://github.com/orgs/elementary/projects/55#card-60206469

**Comment by brodock** [comment]
this seems to be broken on stable release, when trying to open the browser on a new user account. It works with the main user account (I believe it's related to lacking some flatpak on user level)
