### ISSUE TITLE
Feedback app in OS8 fails

### ISSUE THREAD

**Issue by CuriousCoconut** [elementary/browser#152]
### What Happened?

Feedback app closes and doesn't finish launching feedback.

### Steps to Reproduce

On OS8 on the daily and stable builds when opening the feedback and clicking "dock" and then "send feedback" the feedback app disappears and doesn't launch the feedback page where you would actually type the feedback.

### Expected Behavior

After clicking "send feedback" it should go to a webpage (I believe) where you can type details of your issue and submit feedback. 

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Closing in favor of https://github.com/elementary/feedback/issues/115.

Please do not post the same issue in multiple repositories. You might not know where this issue should be reported but it's fine to report issues to a repository that might be out of place by mistake: we can transfer those issues to an appropriate one.

**Comment by CuriousCoconut** [comment]
Okay will do thanks for the help :)
