### ISSUE TITLE
Tab bar has different styling

### ISSUE THREAD

**Issue by Zonnev** [elementary/browser#153]
### What Happened?

I opened Web after some time not using it. I think after a system update I saw this:
![Schermafdruk van 2024-11-24 20 24 14](https://github.com/user-attachments/assets/51fc68a5-01d2-4325-9bc5-0422dea3a8c8)
Web looks different on OS 7. The tab bar and navigation bar had the same colour. I think now it has the same tab bar as Files. Navigation bar is untouched.

### Steps to Reproduce

Open the Web app.

### Expected Behavior

Web should look like in OS 7; navigation bar and tab bar in the same colour.

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This is intentional and it looks how it's supposed to look :)
