### ISSUE TITLE
Patch back/forward button style

### ISSUE THREAD

**Issue by danrabbit** [elementary/browser#16]
## What Happened

back/forward buttons are raised 

## Expected Behavior

they should be flat like Files

**Comment by Exalm** [comment]
Are you sure this isn't a stylesheet issue?

**Comment by cassidyjames** [comment]
I thought last we looked into it, Epiphany was specifically requesting raised styles. If it's not, then it could be because they're linked buttons? Which I also thought was dropped when running on Pantheon, but I'm not sure.

**Comment by Exalm** [comment]
It was, but we stopped doing that upstream. Dropping .linked is a good question, iirc it just added spacing since it was enough on hera.
