### ISSUE TITLE
Epiphany: Double-click in find bar opens new tab

### ISSUE THREAD

**Issue by mcclurgm** [elementary/browser#26]
Migrated from https://gitlab.gnome.org/GNOME/epiphany/issues/839.
This does not occur on the Flatpak build, and Epiphany devs suggest that it's due to Elementary patches. It sounds similar to elementary/os-patches#38, so it could be the same cause.

If I double-click a button on the "find in page" bar, it opens a new tab. This is simply a result of clicking multiple times quickly, which I do often if I want to move down a couple results, or if I double-click to select text in the search field. Of course, any clicks after the second get sent to the new tab page and have no effect on the original.

Specifically, this happens when I double-click on the up/down buttons and the text field. Also, if I double-click a button, only the first one appears to be sent through. The highlighted result moves down by one, not two, so it seems like the double-click behavior intercepts the second click before the button can receive it. However, double-clicking the text field does result in selecting the text (once I tab back to the original), as if I had double-clicked it normally.

I assume that this is the same handler that opens a new tab when you double-click the tab bar, which is also being applied to this other component. I don't know if this is specific to the find bar. I don't think Epiphany has any other similar UIs, like a bookmarks bar, that I could test.

My system:
* Elementary OS 5.0 Juno (up to date as of Jun 30 2019)
* Epiphany version 3.28.5
* WebKitGTK version 2.4.11

**Comment by danrabbit** [comment]
We're no longer patching in the double click behavior so this is technically resolved
