### ISSUE TITLE
Videos in Epiphany appear yellow-purple

### ISSUE THREAD

**Issue by gitwompo** [elementary/browser#27]
I have had this bug since the launch of Juno. Loki was unaffected. I am using the Padoka Stable PPA for more up-to-date graphics drivers (Mesa 18.3.0 at the moment) but this also happens on the default graphics drivers, which at the time of writing are Mesa 18.0.5.
![epiphanyn videobugi - youtube](https://user-images.githubusercontent.com/36341078/49684724-490ce400-fae0-11e8-9bc6-d03cdff7354d.png)
![epiphanyn videobugi - vimeo](https://user-images.githubusercontent.com/36341078/49684725-4a3e1100-fae0-11e8-8c78-e3026100fabb.png)
![jarjestelmatiedot](https://user-images.githubusercontent.com/36341078/49684775-18797a00-fae1-11e8-9165-f404063d71b3.png)
To be more specific than the system information screen: My graphics card is Radeon R9 290. Also, the integrated graphics card is not being used.

On Mozilla Firefox there are no video playback problems whatsoever.

EDIT: My laptop is also affected. System information as follows:
![jarjestelmatiedot](https://user-images.githubusercontent.com/36341078/49684843-24b20700-fae2-11e8-888c-13279b81567e.png)

**Comment by janxkoci** [comment]
Vimeo is crashing Webkit for some reason (I see some gstreamer warning in the terminal), but youtube works without issues:

![Snímek z 2021-06-09 16-45-56](https://user-images.githubusercontent.com/19331850/121376955-40f8be00-c942-11eb-9863-1467f08248b7.png)

**Comment by cassidyjames** [comment]
This might be hardware specific, but I'm unable to reproduce this on any machines (various gens of Intel and NVIDIA). I'm assuming it's resolved by the Flatpak?
