### ISSUE TITLE
Inertia scrolling does not work on touchpads

### ISSUE THREAD

**Issue by kdwk** [elementary/browser#29]
## What Happened

When my fingers are lifted off the touchpad, the scrolling comes to an abrupt halt. This is due to Epiphany not using hardware compositing policy of 'always' but setting it to 'on-demand' instead. This is also an upstream bug, and to this moment I can only get inertia scrolling if I use Dconf Editor to change hardware compositing policy to 'always'. elementary Web should include some workaround for the Flatpak out of the box until this is fixed.

https://user-images.githubusercontent.com/39268094/121765579-7ee22600-cb7e-11eb-913c-d45e5e8feead.mp4

## Expected Behavior

Scrolling decelerates and comes to a gradual stop after I release my fingers from the touchpad

## Steps to Reproduce

1. Open elementary Web
2. Open a website
3. Scroll with a touchpad

## Platform Information

![Screenshot from 2021-06-12 13-03-38](https://user-images.githubusercontent.com/39268094/121765595-a0dba880-cb7e-11eb-91b6-ee807c5433fc.png)

**Comment by Exalm** [comment]
WebKit issue, it's fixed in 2.32.2.

**Comment by hanaral** [comment]
It would probably be solved by rebasing the ref to a newer version since flathub ephy's scrolling is as expected.

**Comment by Exalm** [comment]
It's a webkit bug, so you need newer sdk and not ephy. And yes, it's fixed and released by now.

**Comment by cassidyjames** [comment]
This appears to be shipping in the Flatpak now as I get inertial scrolling again.
