### ISSUE TITLE
Attempting to use the system emoji picker in websites causes the browser to crash

### ISSUE THREAD

**Issue by Schykle** [elementary/browser#39]
## What Happened

Calling the system emoji picker in Web, say in a text field in Twitter or GitHub, etc. causes the browser to crash.

## Expected Behavior

The emoji picker should appear and allow inputting characters into text boxes.

## Steps to Reproduce

1. Open a site like GitHub in Web
2. Activate a text box
3. Press `Ctrl`+`Period` 

## Platform Information
elementary OS 6.0, updated as of 2021-08-16

**Comment by cassidyjames** [comment]
Huh, I thought I had filed this :grimacing: Can confirm.

**Comment by cassidyjames** [comment]
I've confirmed this using Web from Flathub as well, so it might not be elementary OS specific. Upstream report: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1581

**Comment by janxkoci** [comment]
😁️ I think it works fine now. You can close this 😉️
