### ISSUE TITLE
Cannot run most websites (probably missing dependencies)

### ISSUE THREAD

**Issue by pedropaulosuzuki** [elementary/browser#45]
### What Happened?

Hello! Hope everyone is having a great day!

Today I just installed elementaryOS 6 Odin, updated everything through the AppCenter and went into Epiphany (aka GNOME Web) in order to have internet access. I tested it on a very simple website I created myself (<https://www.eppencoders.com.br>) and everything just works. Great! The same can be said about a pretty small web-based snake game I created a while ago, at (<https://pedropaulosuzuki.github.io/snake_game_JS>). Google (<https://www.google.com>) also works fine! So what's the issue?

Well, any other website I tried just did not work. Flathub (<https://flathub.org>), YouTube (<https://www.youtube.com>) and even Github (<https://github.com/elementary>) failed. (Actually Github worked for about 5 seconds and then, all of a sudden, it didn't). I had to install the Flatpak version of Firefox from the terminal in order to even open this issue. And as the installation ended, Epiphany just came back to life!

Thus, I suspect that some dependency was missing and then, when Firefox got installed as a flatpak, everything came back to life. I did not experience that when I installed elementaryOS 6 earlier on a GNOME Boxes instance, so I'm not 100% sure what happened and now I don't think I can reproduce the issue again, unless I reinstall eOS 6, which I don't think is the best idea. Does anyone know how can we check that? Thanks for your time!!

### Steps to Reproduce

1. Installed elementaryOS 6 Odin;
2. Run all current updates from the AppCenter (didn't test on 100% fresh install);
3. Open GNOME Web (Epiphany);
4. Try any of the following websites: Github, Youtube or Flathub.

### Expected Behavior

Expected websites to work. They did not work until I installed Firefox from flathub using terminal commands, which made Epiphany work too, probably due to the installation of some kind of dependency.

Note: I did run 'sudo apt autoremove' earlier and one package got removed, but I don't remember what it was, but I'm pretty sure it had nothing to do with this issue, but it might be a thing, idk.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No logs.
```

### Hardware Info

OS: elementaryOS 6 Odin
CPU: Intel Core i5 4460
GPU: NVIDIA GTX 750 TI 2GB
RAM: 8 GB DDR3 1600 MHz
NVIDIA Driver 470.63.01

**Comment by jhaygood86** [comment]
NVIDIA Flatpak driver issue.

I think this will be solved by this: https://github.com/elementary/appcenter/issues/1583

**Comment by pedropaulosuzuki** [comment]
> NVIDIA Flatpak driver issue.
> 
> I think this will be solved by this: [elementary/appcenter#1583](https://github.com/elementary/appcenter/issues/1583)

Hmm, that explains why everything went pretty smoothly on my GNOME Boxes VM earlier. Glad to know it will be solved soon, I was about to install eOS on my aunt's laptop, but as it uses NVIDIA Graphics, then I guess I'll wait until it gets properly fixed. Thanks for the quick reply!!

**Comment by pedropaulosuzuki** [comment]
Hey! Just fresh installed elementaryOS 6.1 Jólnir and the issue is gone! Closing this one! Nice work everyone!!
