### ISSUE TITLE
Fails to load (something went wrong message) https://elementary.io/

### ISSUE THREAD

**Issue by philclifford** [elementary/browser#49]
### What Happened?

On fresh install in a VM attempting to go ( back ) to https://elementary.io/ fails - website "breaks" the default browser.  Only workaround (given store cache not there either yet) was to side-load firefox.

Not the best first experience.

### Steps to Reproduce

Install 6.0 to a Qemu KVM (via quickemu).
Complete first run
click on web browser
attempt to go to elementary.io
![elementary_fail](https://user-images.githubusercontent.com/8797027/139129082-780cbc2f-00cd-4985-ac96-976643780d8c.png)

### Expected Behavior

Would show site and not require side-loading another browser

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

quickemu --vm elementary-6.0.conf 
Quickemu 2.2.6 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Ubuntu 21.10 running Linux 5.13 (xxxxx)
 - Guest:    Starting elementary-6.0.conf as elementary-6.0
 - CPU:      AMD Ryzen Threadripper 1920X 12-Core Processor
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (linux)
 - Disk:     elementary-6.0/disk.qcow2 (16G)
 - Display:  SDL, virtio-vga, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "elementary-6.0" --port 5930 --spice-shared-dir /home/phil/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-phil ~/Public
 - smbd:     On guest: smb://10.0.2.4/qemu

**Comment by philclifford** [comment]
Reproducible and after enabling coredumpctl I have three crash dumps.  Nearly got there following the blog along but installing the Sdk.Debug failed due to lack of space in the vm disk.  Might resize / rebuild and try again but frankly have other priorities at the moment so it'll be a while if ever ...

**Comment by ryanprior** [comment]
I was also able to reproduce this crash the other day when I installed elementary OS 6 on a new machine (bare metal, not a VM)

**Comment by ryanprior** [comment]
@danrabbit @cassidyjames can you take a look at this? Would it be helpful for me to try and produce a machine image snapshot that demonstrates the problem? This was a showstopper for my install the other day.

**Comment by danrabbit** [comment]
@ryanprior as Michael pointed out, if you can post a crash dump that would be helpful :)

**Comment by philclifford** [comment]
This is fixed for me with 7.0 release so I'll close the issue.
Sorry I couldn't provide more info.
