### ISSUE TITLE
Close button on right in Firefox sync dialog

### ISSUE THREAD

**Issue by danirabbit** [elementary/browser#53]
### What Happened?

The window close button is on the right side of the window in the firefox sync dialog

### Steps to Reproduce

Open the Firefox sync dialog from the import/export menu and see the window control layout

### Expected Behavior

It should follow the system configuration, in this case the left :)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
@danrabbit lmao I reported this upstream like an hour before this issue report :stuck_out_tongue_closed_eyes: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1647
