### ISSUE TITLE
Standard Web Browser

### ISSUE THREAD

**Issue by TreasuredOwl** [elementary/browser#65]
## What Happened
When you open YouTube or another site where there is a video, the whole system simply freezes, the video does not go and the voice on the video further works for itself

## Expected Behavior
Doesn't want to reboot the system every time

## Platform Information

[https://drive.google.com/file/d/1geHpf3SV2PmflxS9S-p5TLPYEkLiNc3R/view?usp=sharing](url)

**Comment by alatiera** [comment]
Seems like a webkit issue, most likely to do with hw decoding, but its probably no longer an issue? There have been a handful of updates in WebkitGTK wrt video playback.

**Comment by danrabbit** [comment]
Yeah I think we've had a few updates shipped in this time so I'm inclined to close.

OP, if you're still experiencing this issue after running all updates feel free to reopen :)
