### ISSUE TITLE
Epiphany should block trackers and related advertisements

### ISSUE THREAD

**Issue by uncertainquark** [elementary/browser#68]
Forgive me for filing this bug here as I couldn't find any repo for the slightly-modified Epiphany being shipped by elementary.

For a company with a strong stance on privacy by design, it is somewhat strange to see the default elementary browser shipping with the setting of "Block advertisements" and "Block trackers" turned off. Even upstream has the settings on, but elementary has explicitly turned it off it seems (?).
![screenshot from 2019-02-27 07-10-48](https://user-images.githubusercontent.com/22585732/53476111-a0936e00-3a97-11e9-9e5a-f8ec70ad129d.png)

**Comment by danirabbit** [comment]
It looks like ad blocking is enabled by default these days :)
