### ISSUE TITLE
Either add elementary stylesheet or build with elementary SDK

### ISSUE THREAD

**Issue by danrabbit** [elementary/browser#7]
## What Happened

Epiphany is back to using Adwaita again as the stylesheet

## Expected Behavior

Epiphany should use the elementary stylesheet. We have a couple of options here: 

* We could add the stylesheet itself to the flatpak
* We could use the elementary Sdk. However, I'm not sure that Epiphany 40 will build against elementary Sdk since it's currently based on the GNOME 3.38 Sdk.

**Comment by Exalm** [comment]
It bundles the stylesheet and icons on Flathub: https://github.com/flathub/org.gnome.Epiphany/blob/master/org.gnome.Epiphany.json#L19-L99

**Comment by Marukesu** [comment]
The manifest on this repo runs with `--runtime=io.elementary.Platform//0.1.0`, same for the Devel.
