### ISSUE TITLE
Info about...

### ISSUE THREAD

**Issue by Odi-3** [elementary/browser#81]
### What Happened?

In some GNOME applications there is an "Info about..." button in the main application menu. In Web, however, it is no longer present. So what is the correct choice?

### Steps to Reproduce

1. Open a GNOME application
2. Open the main application menu

### Expected Behavior

Make one choice for all GNOME applications

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by Odi-3** [comment]
So the same will be done for other Gnome applications?

**Comment by danirabbit** [comment]
It looks like they're removing this item upstream in Epiphany, so please file an issue report there: https://gitlab.gnome.org/GNOME/epiphany/-/blob/master/src/ephy-header-bar.c#L335

Closing as "Out of scope" since this is an upstream issue and we don't do anything about this downstream

**Comment by Exalm** [comment]
In all fairness, upstream is doing it because you were hiding it with a patch before that :)

**Comment by mcatanzaro** [comment]
Yeah, so do you want it or not? :P It must have been originally removed by either you or Cassidy.

**Comment by mcatanzaro** [comment]
It looks like the user help is also removed when running on Pantheon, although I suppose that's because the screenshots will look foreign.

**Comment by danirabbit** [comment]
Ah, I'm indifferent on it. If you think there's information there that users would find valuable or just wanna remove a special case then 👍

There's enough things in Epiphany that aren't quite what we do in our apps that I don't think it's going to "break immersion" or anything 😅
