### ISSUE TITLE
Performance significantly slower than that of epiphany from flatpak (gnome nightly)

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/browser#92]
### What Happened?

GNOME Web from eOS 7 is very slow and doesn't even load github at all. the one from gnome nightly takes some time to load, but it's not as bad*

### Steps to Reproduce

1. Get eOS 7 on good hardware & good internet connection
2. Open GNOME Web. Try to login to github.
3. You will notice it wont load until you resize the window. even after that, its unusable.
4. Get the flatpak source from gnome nightly: `flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo`
5. `flatpak install gnome-nightly org.gnome.Epiphany.Devel` and `flatpak run org.gnome.Epiphany.Devel//master`
6. You can at least browse github and login succesfully

### Expected Behavior

GNOME Web on eOS7 should auto update to latest stable (?)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I'm on generic drivers (Ryzen 7 2700X, 5500XT), other than that everything is ok :) no other app shows glitches/freezes.

Edit: workaround by adding `window.clipboard = {};` on Gnome web custom JS file.

**Comment by danirabbit** [comment]
We're already working on it. Please be patient. It just came out last week :)

**Comment by aitor-gomila** [comment]
Oh, no worries! What's the issue?

**Comment by danirabbit** [comment]
Requires some platform updates. Should be out in the next couple days.

> Didn't intend to sound like a jerk or anything like that

Calling people's projects "shit" is probably something you should stop doing then

**Comment by aitor-gomila** [comment]
> Calling people's projects "shit" is probably something you should stop doing then

What?

**Comment by mcatanzaro** [comment]
> We're already working on it. Please be patient. It just came out last week :)

So we discovered earlier today that [you're still shipping WebKitGTK 2.38.1](https://gitlab.gnome.org/GNOME/epiphany/-/issues/2003#note_1709940), so it seems you're just not updating WebKitGTK at all. You do not need to update to Epiphany to fix github.com. Just updating WebKitGTK 2.40.0 will suffice.

[Release history](https://webkitgtk.org/news.html)

**Comment by danirabbit** [comment]
@mcatanzaro we have a platform build queued that includes newer WebKit already, so we're fixing both at the same time

**Comment by mcatanzaro** [comment]
> Also, my GNOME gitlab account got deleted during the spam purge and when I tried to recreate it, it was automatically deleted again. So I'm not getting pings there sorry

[You're not currently deleted.](https://gitlab.gnome.org/danrabbit) Maybe the somebody noticed and restored the account? Dunno what happened there.

**Comment by aitor-gomila** [comment]
Closing because I'm able to browse GitHub now
